name: huawei_push_example
description: Demonstrates how to use the huawei_push plugin.

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0 <3.39.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_push:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
