group "com.huawei.hms.flutter.push"
version "1.0"

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://developer.huawei.com/repo/" }
    }

    dependencies {
        classpath "com.android.tools.build:gradle:8.8.0"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://developer.huawei.com/repo/" }
    }
}

apply plugin: "com.android.library"

android {
    compileSdkVersion 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 35
    }

    lintOptions {
        disable "InvalidPackage"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation "com.huawei.hms:push:6.13.0.300"
    implementation "com.facebook.fresco:fresco:3.6.0"
}
